### ISSUE TITLE
Integrating with docker compose

### ISSUE THREAD

**Issue by shwarzes89** [naver/pinpoint#3826]
#### Description

안녕하세요,
spring boot (embedded tomcat, 8080포트에서 실행) 와 docker-compose로 pinpoint를 연동할 때 
작동이 되지 않아 문의드립니다. pinpoint들의 컴포넌트는 아래의 docker compose파일로부터 실행(profiler.sampling.rate=2 으로) 시켰습니다.
pinpoint web에서 정상적으로 application을 인지하고 메모리, cpu 사용량을 측정하나 메소드 trace및 connection
부분은 수집이 되지 않는 것 같습니다. 

아마 포트나 연결 ip부분으로 인한것으로 추정되는데, 혹시 어느 설정파일 부분을 수정해야 할 지 알려주시면 감사하겠습니다.

Good morning,
When using the spring boot (embedded tomcat, running on the 8080 port) and docker-compose with pinpoint has some problem. The components of the pinpoints were run from the following docker compose file (profiler.sampling.rate = 2).
Pinpoint web application normally recognizes memory and cpu usage but it cant collect method trace and connection data.

It is probably due to the port or connection ip part, and I would appreciate it if you let me know which configuration file part you need to modify.

#### Environment

* Pinpoint version: 1.7.1
* OS, WAS, affected library, etc:
* Additional details (e.g. how your collector/web is set up):

```yaml
pinpoint-hbase:
  container_name: pinpoint-hbase
  hostname: hbase
  image: minyk/pinpoint-hbase:1.7.1
  restart: always
  expose:
    - "2181"
    - "16010"
  ports:
    - "2181:2181"
    - "16010:16010"

pinpoint-mysql:
  container_name: pinpoint-mysql
  restart: always
  image: mysql:5.7
  ports:
    - "13306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=
    - MYSQL_USER=
    - MYSQL_PASSWORD=
    - MYSQL_DATABASE=

pinpoint-collector:
  container_name: pinpoint-collector
  hostname: collector
  image: minyk/pinpoint-collector:1.7.1
  restart: always
  expose:
    - "9994"
    - "9995"
    - "9996"
  ports:
    - "9994:9994"
    - "9995:9995/tcp"
    - "9996:9996/tcp"
    - "9995:9995/udp"
    - "9996:9996/udp"
  environment:
    HBASE_HOST: hbase
    HBASE_PORT: 2181
    COLLECTOR_TCP_PORT: 9994
    COLLECTOR_UDP_STAT_LISTEN_PORT: 9995
    COLLECTOR_UDP_SPAN_LISTEN_PORT: 9996
    CLUSTER_ENABLE: 'true'
    CLUSTER_ZOOKEEPER_ADDRESS: hbase
    DISABLE_DEBUG: 'true'
  links:
    - pinpoint-hbase:hbase

pinpoint-web:
  container_name: pinpoint-web
  hostname: web
  image: minyk/pinpoint-web:1.7.1
  restart: always
  expose:
    - "8080"
  ports:
    - "3080:8080"
  environment:
    HBASE_HOST: hbase
    HBASE_PORT: 2181
    CLUSTER_ENABLE: 'true'
    CLUSTER_ZOOKEEPER_ADDRESS: hbase
    ADMIN_PASSWORD:
    DISABLE_DEBUG: 'true'
    JDBC_DRIVER: com.mysql.jdbc.Driver
    JDBC_URL: jdbc:mysql://mysql:3306/pinpoint?characterEncoding=UTF-8
    JDBC_USERNAME:
    JDBC_PASSWORD:
  links:
    - pinpoint-hbase:hbase
    - pinpoint-mysql:mysql
```
